---
- name: Fix resolv.conf file
  hosts: "{{ target | default('all') }}"
  tasks:
    - name: Copy resolv.conf
      copy: >
        src=../files/resolv.conf.lab
        dest=/etc/resolv.conf
        owner=root
        group=root
        mode=0644

    - name: ifup eth1
      shell: 'ifup eth1'
      ignore_errors: yes
